---
version: 2.1

executors:
  delivery:
    docker: [image: "chef/chefdk:4.0.5"]
  ruby:
    docker: [image: "circleci/ruby"]
  python:
    docker: [image: "circleci/python"]
  chef:
    machine:
      image: "circleci/classic:201808-01"

commands:
  install_chef:
    description: Installs Chef Development Kit
    parameters:
      channel:
        description: 'Ubuntu channel: stable | current.'
        type: string
        default: 'stable'
      distribution:
        description: 'Ubuntu release: bionic|trusty|xenial'
        type: string
        default: 'bionic'
      version:
        description: ChefDK semver number 
        type: string
        default: '3.9.0-1'
    steps:
      - run:
          name: Install Chef
          command: |
            while sudo fuser /var/{lib/{dpkg,apt/lists},cache/apt/archives}/lock >/dev/null 2>&1; do
              sudo lsof /var/lib/dpkg/lock
              tail /var/log/unattended-upgrades/unattended-upgrades-dpkg.log || true
              killall apt-get || true
              killall dpkg || true
              sleep 1
            done
            sudo chmod 646 /etc/apt/sources.list
            echo "deb https://packages.chef.io/repos/apt/<<parameters.channel>> <<parameters.distribution>> main" |tee -a /etc/apt/sources.list
            wget -qO - https://packages.chef.io/chef.asc | sudo apt-key add -
            sudo apt-get update
            sudo apt-get install apt-transport-https
            sudo CHEF_LICENSE='accept' DEBIAN_FRONTEND=noninteractive apt-get install chefdk=<<parameters.version>>
            

jobs:
  danger:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Install Danger
          command: gem install danger
      - run:
          name: Run Danger
          command: danger
  delivery:
    executor: delivery
    steps:
      - checkout
      - run:
          name: Run delivery
          command: delivery local all
  dokken:
    executor: chef
    parameters:
      suite:
        description: Test Kitchen suite name
        type: string
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
      timeout:
        description: Set the command timeout
        type: string
        default: 2h
    environment:
      KITCHEN_LOCAL_YAML: kitchen.yml
      CHEF_LICENSE: "accept"
    steps:
      - checkout
      - install_chef:
          channel: <<parameters.channel>>
      - run:
          name: amazonlinux
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-amazonlinux
      - run:
          name: amazonlinux-2
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-amazonlinux-2
      - run:
          name: centos-6
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-centos-6
      - run:
          name: centos-7
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-centos-7
      - run:
          name: debian-8
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-debian-8
      - run:
          name: debian-9
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-debian-9
      - run:
          name: ubuntu-16.04
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-ubuntu-1604
      - run:
          name: ubuntu-18.04
          no_output_timeout: <<parameters.timeout>>
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>-ubuntu-1804
      - store_artifacts:
          path: .kitchen/logs
          when: always

  dokken-single:
    executor: chef
    parameters:
      suite:
        description: Test Kitchen suite name
        type: string
      channel:
        description: ChefDK channel stable or current
        type: string
        default: current
    environment:
      KITCHEN_LOCAL_YAML: kitchen.yml
      CHEF_LICENSE: "accept-no-persist"
    steps:
      - checkout
      - install_chef:
          channel: <<parameters.channel>>
      - run:
          command: CHEF_LICENSE="accept-no-persist" kitchen test <<parameters.suite>>
      - store_artifacts:
          path: .kitchen/logs
          when: always
  mdlint:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Install Markdown Linter
          command: gem install mdl
      - run:
          name: Run Markdown Linter
          command: mdl ./
  yamllint:
    executor: python
    steps:
      - checkout
      - run:
          name: Install YamlLint
          command: pip install --user yamllint
      - run:
          name: Run YamlLint
          command: |
            export PATH=/home/circleci/.local/bin:$PATH
            yamllint -d relaxed .